// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nahhas.Library;

namespace Nahhas.Library.Migrations
{
    [DbContext(typeof(NahhasDbContext))]
    [Migration("20210613205004_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nahhas.Library.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AdditionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("StatusCount")
                        .HasColumnType("decimal(38,0)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2bb6ed74-970f-4b88-9f50-9a46aeb05f06"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 173, DateTimeKind.Utc).AddTicks(7974),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 173, DateTimeKind.Utc).AddTicks(8748),
                            Name = "0th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("bfd100d8-e04d-48c9-8c85-3517ade8a4d0"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3342),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3344),
                            Name = "1th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("2ae9104e-9557-49dc-b505-60ef9f992718"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3516),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3517),
                            Name = "2th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("67b3b238-43e2-4474-8cc1-e2051581d072"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3604),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3605),
                            Name = "3th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("c6d2d0f7-c8ce-42e0-a13d-9f40de6bac4d"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3744),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3745),
                            Name = "4th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("b36fc3eb-c009-4cff-8c83-3133cefadeed"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3840),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3841),
                            Name = "5th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("41c356c6-183d-4d65-94f3-8a0afc75088a"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3929),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3930),
                            Name = "6th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("f275ea2b-2017-4669-9d3e-c4056020d5f3"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4046),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4048),
                            Name = "7th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("ffa09755-ab22-4f4c-997c-02f23ee65e38"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4135),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4136),
                            Name = "8th Love",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("2be86752-e929-4533-9b06-a3a8ebeca32f"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4306),
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4308),
                            Name = "9th Love",
                            StatusCount = 0m
                        });
                });

            modelBuilder.Entity("Nahhas.Library.Entities.Statuses.Base.StatusBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AdditionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DownloadsCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LikesCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<decimal>("SharesCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<decimal>("ViewsCount")
                        .HasColumnType("decimal(38,0)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Status");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StatusBase");
                });

            modelBuilder.Entity("Nahhas.Library.Entities.Statuses.Image", b =>
                {
                    b.HasBaseType("Nahhas.Library.Entities.Statuses.Base.StatusBase");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Image");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68530729-797b-4bf0-9ffb-813d4352ed8b"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(2308),
                            CategoryId = new Guid("2bb6ed74-970f-4b88-9f50-9a46aeb05f06"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(2311),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("0b933dc0-6cd7-4e71-83c9-4a0b7ceacb7b"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3457),
                            CategoryId = new Guid("bfd100d8-e04d-48c9-8c85-3517ade8a4d0"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3458),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("d521c987-2dfc-4f46-a2a5-314f4cb53ab1"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3561),
                            CategoryId = new Guid("2ae9104e-9557-49dc-b505-60ef9f992718"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3562),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("6a956424-afe0-4491-844a-d8946b8725b2"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3700),
                            CategoryId = new Guid("67b3b238-43e2-4474-8cc1-e2051581d072"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3701),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("b2d1dfa9-2b8e-4504-bbfe-08d5c9e8798c"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3794),
                            CategoryId = new Guid("c6d2d0f7-c8ce-42e0-a13d-9f40de6bac4d"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3795),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("3fde3da4-696a-42be-904a-0826eda5b94d"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3883),
                            CategoryId = new Guid("b36fc3eb-c009-4cff-8c83-3133cefadeed"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3885),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("6e674da7-0edf-4b4c-be99-6672394396df"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3972),
                            CategoryId = new Guid("41c356c6-183d-4d65-94f3-8a0afc75088a"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3973),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("726dc643-5986-427c-b3e5-30f96a886079"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4090),
                            CategoryId = new Guid("f275ea2b-2017-4669-9d3e-c4056020d5f3"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4091),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("558568f3-9bc1-486f-bb44-d38334a4dfde"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4183),
                            CategoryId = new Guid("ffa09755-ab22-4f4c-997c-02f23ee65e38"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4184),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        },
                        new
                        {
                            Id = new Guid("518671bb-d2f8-4b58-b9ed-e78a96f4749c"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4357),
                            CategoryId = new Guid("2be86752-e929-4533-9b06-a3a8ebeca32f"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4358),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png"
                        });
                });

            modelBuilder.Entity("Nahhas.Library.Entities.Statuses.Quote", b =>
                {
                    b.HasBaseType("Nahhas.Library.Entities.Statuses.Base.StatusBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Quote");

                    b.HasData(
                        new
                        {
                            Id = new Guid("422cbc64-aaa9-437b-92a6-f3a5138a9a19"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3161),
                            CategoryId = new Guid("2bb6ed74-970f-4b88-9f50-9a46aeb05f06"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3165),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "0th Quote."
                        },
                        new
                        {
                            Id = new Guid("1d50f4a0-1b83-4960-8dfe-3699796fd077"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3483),
                            CategoryId = new Guid("bfd100d8-e04d-48c9-8c85-3517ade8a4d0"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3484),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "1th Quote."
                        },
                        new
                        {
                            Id = new Guid("dfd53def-b1aa-4698-9071-a248078c1e02"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3583),
                            CategoryId = new Guid("2ae9104e-9557-49dc-b505-60ef9f992718"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3584),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "2th Quote."
                        },
                        new
                        {
                            Id = new Guid("3bf2e138-2496-4b90-8c7c-0e3e42422f69"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3721),
                            CategoryId = new Guid("67b3b238-43e2-4474-8cc1-e2051581d072"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3721),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "3th Quote."
                        },
                        new
                        {
                            Id = new Guid("32886cc8-04a7-4962-a581-80bb33166c7a"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3816),
                            CategoryId = new Guid("c6d2d0f7-c8ce-42e0-a13d-9f40de6bac4d"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3818),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "4th Quote."
                        },
                        new
                        {
                            Id = new Guid("e9009548-a9a6-4b83-8c52-2397281d0dc6"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3905),
                            CategoryId = new Guid("b36fc3eb-c009-4cff-8c83-3133cefadeed"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3906),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "5th Quote."
                        },
                        new
                        {
                            Id = new Guid("4eac6584-a117-4d4f-ba94-f86cf673f3e2"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4023),
                            CategoryId = new Guid("41c356c6-183d-4d65-94f3-8a0afc75088a"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4024),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "6th Quote."
                        },
                        new
                        {
                            Id = new Guid("79fa2e2e-df3b-4d55-8c52-14428813ec66"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4112),
                            CategoryId = new Guid("f275ea2b-2017-4669-9d3e-c4056020d5f3"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4113),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "7th Quote."
                        },
                        new
                        {
                            Id = new Guid("482d1d04-412e-47d7-a6e2-1837f7c4b9bf"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4206),
                            CategoryId = new Guid("ffa09755-ab22-4f4c-997c-02f23ee65e38"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4207),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "8th Quote."
                        },
                        new
                        {
                            Id = new Guid("1c7de042-6c56-4d62-a7c9-4eead1f9502b"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4378),
                            CategoryId = new Guid("2be86752-e929-4533-9b06-a3a8ebeca32f"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4379),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "9th Quote."
                        });
                });

            modelBuilder.Entity("Nahhas.Library.Entities.Statuses.Video", b =>
                {
                    b.HasBaseType("Nahhas.Library.Entities.Statuses.Base.StatusBase");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Video");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94352c7b-b5b9-424b-8550-f2c5d7569ebb"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(1426),
                            CategoryId = new Guid("2bb6ed74-970f-4b88-9f50-9a46aeb05f06"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(1431),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "0th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("761f7954-98f0-4921-8598-4f2ce0e42a0f"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3429),
                            CategoryId = new Guid("bfd100d8-e04d-48c9-8c85-3517ade8a4d0"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3430),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "1th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("51d6d0c4-b0f6-4823-a58e-5b3ef4da38ed"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3539),
                            CategoryId = new Guid("2ae9104e-9557-49dc-b505-60ef9f992718"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3540),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "2th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("365ee8a9-c9fc-464e-b733-4dc5df21bfa0"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3675),
                            CategoryId = new Guid("67b3b238-43e2-4474-8cc1-e2051581d072"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3676),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "3th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("96eb92be-25c0-4fcd-a140-8f0e7b09329b"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3772),
                            CategoryId = new Guid("c6d2d0f7-c8ce-42e0-a13d-9f40de6bac4d"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3773),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "4th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("6a5904c4-56fb-498c-9de6-bfe1df6ce9f6"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3862),
                            CategoryId = new Guid("b36fc3eb-c009-4cff-8c83-3133cefadeed"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3863),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "5th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("405665e0-71cf-4204-9fb6-9c96ec1c99b4"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3951),
                            CategoryId = new Guid("41c356c6-183d-4d65-94f3-8a0afc75088a"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(3952),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "6th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("d5c39059-60c2-4404-82e4-049ff57254ad"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4069),
                            CategoryId = new Guid("f275ea2b-2017-4669-9d3e-c4056020d5f3"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4070),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "7th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("a18e40aa-83f8-448d-a65c-168565f5f835"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4160),
                            CategoryId = new Guid("ffa09755-ab22-4f4c-997c-02f23ee65e38"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4161),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "8th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        },
                        new
                        {
                            Id = new Guid("ec073a8d-0e3a-475c-9883-ff9b1f66660c"),
                            Active = true,
                            AdditionDate = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4335),
                            CategoryId = new Guid("2be86752-e929-4533-9b06-a3a8ebeca32f"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(2021, 6, 13, 20, 50, 4, 175, DateTimeKind.Utc).AddTicks(4336),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/images/2021-6-11-21-5-20-31-14542525338141bbbf215cecf7561b11.png",
                            Title = "9th Video",
                            VideoPath = "https://nahhasapi20210611231706.azurewebsites.net/statuses/videos/2021-6-11-21-5-5-108-8668c83aeb6b49e3905939b375c9c11d.mp4"
                        });
                });

            modelBuilder.Entity("Nahhas.Library.Entities.Statuses.Base.StatusBase", b =>
                {
                    b.HasOne("Nahhas.Library.Entities.Category", "Category")
                        .WithMany("Statuses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Nahhas.Library.Entities.Category", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
