// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nahhas.Shared;

namespace Nahhas.Shared.Migrations
{
    [DbContext(typeof(NahhasDbContext))]
    [Migration("20210610125952_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nahhas.Shared.Entities.Base.StatusBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DownloadsCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LikesCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<decimal>("SharesCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<decimal>("ViewsCount")
                        .HasColumnType("decimal(38,0)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Status");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StatusBase");
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("StatusCount")
                        .HasColumnType("decimal(38,0)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3df42c31-ae20-4f90-b3d5-88eda4b43123"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk0",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("995cc707-fdb7-4cb8-b061-a8b07cf5382d"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk1",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("bc64a4b9-7d58-41a2-b135-779bc5f08b34"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk2",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("d76acd47-f978-4dae-bd22-eccfe0e8fccc"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk3",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("7a4ec1f9-9f7c-42c4-841a-7e7001a38eeb"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk4",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("57eea60b-b850-4249-bce1-a31b4eddc0c2"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk5",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("a70f13d0-d014-437a-be32-b64a6f8bea13"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk6",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("04fd3992-5114-446a-8e6b-744f961e7cb1"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk7",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("32a68bf3-6ba5-46d6-8e78-ae160fe542bf"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk8",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("a6364963-5d0a-4739-b9e8-0a82c1052c1e"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk9",
                            StatusCount = 0m
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Image", b =>
                {
                    b.HasBaseType("Nahhas.Shared.Entities.Base.StatusBase");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Image");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f9776a4-5143-40a8-8511-9268d80546bd"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("3df42c31-ae20-4f90-b3d5-88eda4b43123"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("6f1c1417-c013-43fb-b720-049b15d1cfdb"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("995cc707-fdb7-4cb8-b061-a8b07cf5382d"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("f519695f-6d2b-4b53-b456-4972282141c0"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("bc64a4b9-7d58-41a2-b135-779bc5f08b34"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("42543e78-9184-47c9-b516-67c22c623660"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("d76acd47-f978-4dae-bd22-eccfe0e8fccc"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("ad11e9e3-86b5-401b-aec4-2cdd87814272"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("7a4ec1f9-9f7c-42c4-841a-7e7001a38eeb"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("ffb876bc-4fd5-444b-8ed7-ab6ab0d40e46"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("57eea60b-b850-4249-bce1-a31b4eddc0c2"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("68f1140f-ff0a-4160-8474-a92862a84d1c"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("a70f13d0-d014-437a-be32-b64a6f8bea13"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("0dee24fa-5193-4edd-b6ee-8560b771d1ca"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("04fd3992-5114-446a-8e6b-744f961e7cb1"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("13db8e80-bf56-4e6a-b29b-c08286da6e7d"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("32a68bf3-6ba5-46d6-8e78-ae160fe542bf"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("87ee2357-c187-495e-b8db-56d1eb9c5402"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("a6364963-5d0a-4739-b9e8-0a82c1052c1e"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Quote", b =>
                {
                    b.HasBaseType("Nahhas.Shared.Entities.Base.StatusBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Quote");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e67789d-bd9c-418e-9d79-64df05f58918"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("3df42c31-ae20-4f90-b3d5-88eda4b43123"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 0th Status."
                        },
                        new
                        {
                            Id = new Guid("08e1a09c-1462-42dc-bb68-c408a9ce28fc"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("995cc707-fdb7-4cb8-b061-a8b07cf5382d"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 1th Status."
                        },
                        new
                        {
                            Id = new Guid("ed66e9f6-9dfb-4913-b982-98cc83d5ebcb"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("bc64a4b9-7d58-41a2-b135-779bc5f08b34"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 2th Status."
                        },
                        new
                        {
                            Id = new Guid("2e484998-35ae-414c-9b60-e8a83dc61254"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("d76acd47-f978-4dae-bd22-eccfe0e8fccc"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 3th Status."
                        },
                        new
                        {
                            Id = new Guid("ac54a66f-67f2-40c2-84f1-12e230496383"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("7a4ec1f9-9f7c-42c4-841a-7e7001a38eeb"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 4th Status."
                        },
                        new
                        {
                            Id = new Guid("aae62f60-76ac-422f-bca4-32436089a281"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("57eea60b-b850-4249-bce1-a31b4eddc0c2"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 5th Status."
                        },
                        new
                        {
                            Id = new Guid("58cdcf35-018d-411c-bc64-58be070b07c8"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("a70f13d0-d014-437a-be32-b64a6f8bea13"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 6th Status."
                        },
                        new
                        {
                            Id = new Guid("c6c4bbf0-f707-46e7-9686-d118d68fb42c"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("04fd3992-5114-446a-8e6b-744f961e7cb1"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 7th Status."
                        },
                        new
                        {
                            Id = new Guid("7f93d7d4-780d-4397-8a01-f5d56a496904"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("32a68bf3-6ba5-46d6-8e78-ae160fe542bf"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 8th Status."
                        },
                        new
                        {
                            Id = new Guid("0cd292b0-debc-4f7e-8ba9-1731f93d8bae"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("a6364963-5d0a-4739-b9e8-0a82c1052c1e"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 9th Status."
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Video", b =>
                {
                    b.HasBaseType("Nahhas.Shared.Entities.Base.StatusBase");

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Video");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6966898-c8c9-487d-905c-52a399d7b2dd"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("3df42c31-ae20-4f90-b3d5-88eda4b43123"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer0",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("845e982d-63a8-4147-a9b6-17803daab14f"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("995cc707-fdb7-4cb8-b061-a8b07cf5382d"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer1",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("8ad39a36-ba70-4616-8614-1e7c79e1c174"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("bc64a4b9-7d58-41a2-b135-779bc5f08b34"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer2",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("313f273f-d621-4ae0-aa6f-4c4224558dd5"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("d76acd47-f978-4dae-bd22-eccfe0e8fccc"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer3",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("505f80fe-bf0d-4788-aea5-77dfeb55473b"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("7a4ec1f9-9f7c-42c4-841a-7e7001a38eeb"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer4",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("b9a4afc5-9292-44e1-9612-b66701132cfd"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("57eea60b-b850-4249-bce1-a31b4eddc0c2"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer5",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("3cd5ec4c-3d55-43cd-bb48-fde7d7ee90bd"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("a70f13d0-d014-437a-be32-b64a6f8bea13"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer6",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("2d399b56-e8e8-4c14-a2d3-ec7125878c9b"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("04fd3992-5114-446a-8e6b-744f961e7cb1"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer7",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("bcd849c3-2416-4b6b-a5ea-c68c3788760c"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("32a68bf3-6ba5-46d6-8e78-ae160fe542bf"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer8",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("90fe957d-f0a4-4dba-8712-753504d7c147"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("a6364963-5d0a-4739-b9e8-0a82c1052c1e"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Sevgililer9",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Base.StatusBase", b =>
                {
                    b.HasOne("Nahhas.Shared.Entities.Category", "Category")
                        .WithMany("Statuses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Category", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
