// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nahhas.Shared;

namespace Nahhas.Shared.Migrations
{
    [DbContext(typeof(NahhasDbContext))]
    partial class NahhasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nahhas.Shared.Entities.Base.StatusBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DownloadsCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LikesCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<decimal>("SharesCount")
                        .HasColumnType("decimal(38,0)");

                    b.Property<decimal>("ViewsCount")
                        .HasColumnType("decimal(38,0)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Status");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StatusBase");
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("StatusCount")
                        .HasColumnType("decimal(38,0)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ea1815-a784-4c6a-9dfc-c1968f9682d8"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk00",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("b7fba040-6b10-47bc-9156-ad0f14dcc59b"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk11",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("e4c9ff42-062a-41fe-b224-42ec0cd6eaa8"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk22",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("1938172f-3f01-491a-81c2-d766e421ed79"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk33",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("3bdfc502-ab52-4860-b6a7-77f473ef91e3"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk44",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("07943d46-e463-494d-97ab-9bc81c623394"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk55",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("022cca00-53b3-429d-8ce7-c39c049589e1"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk66",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("27dfda8a-4672-44d8-8cb3-7a0228595bc8"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk77",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("125664d7-5517-4fdb-821c-45a7bead61b2"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk88",
                            StatusCount = 0m
                        },
                        new
                        {
                            Id = new Guid("ed969ad4-a203-48d8-bd6f-40bdcec5c531"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşk99",
                            StatusCount = 0m
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Image", b =>
                {
                    b.HasBaseType("Nahhas.Shared.Entities.Base.StatusBase");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Image");

                    b.HasData(
                        new
                        {
                            Id = new Guid("422846b3-9082-4a03-9cec-f93cb47d0a65"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("22ea1815-a784-4c6a-9dfc-c1968f9682d8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("92927a74-9a2b-455b-9d36-cea3580d4202"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("b7fba040-6b10-47bc-9156-ad0f14dcc59b"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("cffda42c-9e7b-4d91-962e-3f9035bba011"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("e4c9ff42-062a-41fe-b224-42ec0cd6eaa8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("47b62055-ce7c-426a-82a0-84a4a1f0a057"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("1938172f-3f01-491a-81c2-d766e421ed79"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("61c3a8cc-7558-42d4-acfa-7dabe2d2e266"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("3bdfc502-ab52-4860-b6a7-77f473ef91e3"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("ebe4451c-88cc-4739-9b0a-633d11b7bea0"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("07943d46-e463-494d-97ab-9bc81c623394"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("027fab0c-29be-49c6-a948-224b1e3a04e9"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("022cca00-53b3-429d-8ce7-c39c049589e1"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("fc8cd28e-7f2a-4bac-941a-a7d691e10b7c"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("27dfda8a-4672-44d8-8cb3-7a0228595bc8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("90d509f5-9863-44d9-919b-6a7753ad2f9e"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("125664d7-5517-4fdb-821c-45a7bead61b2"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        },
                        new
                        {
                            Id = new Guid("37661303-c6ec-4265-9217-f4033760e990"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("ed969ad4-a203-48d8-bd6f-40bdcec5c531"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            ImagePath = "https://localhost:44308/statuses/images/a.png"
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Quote", b =>
                {
                    b.HasBaseType("Nahhas.Shared.Entities.Base.StatusBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Quote");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3c5cd89-edbf-4921-a074-be31250576ad"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("22ea1815-a784-4c6a-9dfc-c1968f9682d8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 0. Status."
                        },
                        new
                        {
                            Id = new Guid("a912e314-8929-4190-babc-132ba7b7f9f3"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("b7fba040-6b10-47bc-9156-ad0f14dcc59b"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 1. Status."
                        },
                        new
                        {
                            Id = new Guid("0505f08c-c583-4084-8a1c-7d5603814e18"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("e4c9ff42-062a-41fe-b224-42ec0cd6eaa8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 2. Status."
                        },
                        new
                        {
                            Id = new Guid("3b8448de-17dd-4e24-b35b-9b6277cd644d"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("1938172f-3f01-491a-81c2-d766e421ed79"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 3. Status."
                        },
                        new
                        {
                            Id = new Guid("ed9f8e09-4522-4ffe-b3a8-7b4872bc7ddc"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("3bdfc502-ab52-4860-b6a7-77f473ef91e3"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 4. Status."
                        },
                        new
                        {
                            Id = new Guid("f0919e7f-e095-466f-9931-7411aa536881"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("07943d46-e463-494d-97ab-9bc81c623394"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 5. Status."
                        },
                        new
                        {
                            Id = new Guid("bf675447-6638-4df6-9a56-aacfadfe1f65"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("022cca00-53b3-429d-8ce7-c39c049589e1"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 6. Status."
                        },
                        new
                        {
                            Id = new Guid("db124b9f-2519-4517-beaa-63d032b2b76e"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("27dfda8a-4672-44d8-8cb3-7a0228595bc8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 7. Status."
                        },
                        new
                        {
                            Id = new Guid("59c4ab57-123b-42c1-a3fc-0644a45a6943"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("125664d7-5517-4fdb-821c-45a7bead61b2"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 8. Status."
                        },
                        new
                        {
                            Id = new Guid("f16241e9-e251-4caa-8741-8c154c082973"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("ed969ad4-a203-48d8-bd6f-40bdcec5c531"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            Content = "My 9. Status."
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Video", b =>
                {
                    b.HasBaseType("Nahhas.Shared.Entities.Base.StatusBase");

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Status");

                    b.HasDiscriminator().HasValue("Video");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fdeb62f-0651-4aa6-a5fc-057b7461ade1"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("22ea1815-a784-4c6a-9dfc-c1968f9682d8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk0",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("e5df096f-cbac-439d-810e-7003f90df768"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("b7fba040-6b10-47bc-9156-ad0f14dcc59b"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk1",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("e29f5e81-b85a-429a-a871-2b379a6f13e0"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("e4c9ff42-062a-41fe-b224-42ec0cd6eaa8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk2",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("5aed5313-39ef-4bd5-9f89-95410bb9152c"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("1938172f-3f01-491a-81c2-d766e421ed79"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk3",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("289d3ab1-06ba-4c03-9647-db3b4559563d"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("3bdfc502-ab52-4860-b6a7-77f473ef91e3"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk4",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("63d61a48-ea03-454e-be43-51b91350f297"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("07943d46-e463-494d-97ab-9bc81c623394"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk5",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("88f30ada-66e7-4c94-8f34-8285607c488c"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("022cca00-53b3-429d-8ce7-c39c049589e1"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk6",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("a89ac403-6127-42a3-91a3-dcfb38d08181"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("27dfda8a-4672-44d8-8cb3-7a0228595bc8"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk7",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("4f1896e9-e38b-4c2f-abec-6d1dfa274de2"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("125664d7-5517-4fdb-821c-45a7bead61b2"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk8",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        },
                        new
                        {
                            Id = new Guid("4045a98a-b289-436e-9512-e21db9b31d0b"),
                            Active = true,
                            AdditionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = new Guid("ed969ad4-a203-48d8-bd6f-40bdcec5c531"),
                            DownloadsCount = 0m,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesCount = 0m,
                            SharesCount = 0m,
                            ViewsCount = 0m,
                            CoverPath = "https://localhost:44308/statuses/images/a.png",
                            Title = "Aşk9",
                            VideoPath = "https://localhost:44308/statuses/videos/a.mp4"
                        });
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Base.StatusBase", b =>
                {
                    b.HasOne("Nahhas.Shared.Entities.Category", "Category")
                        .WithMany("Statuses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Nahhas.Shared.Entities.Category", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
